cd "$( dirname "$0" )"
ln -sf "$(pwd)/.gemrc" "$HOME/.gemrc"
ln -sf "$(pwd)/.irbrc" "$HOME/.irbrc"
ln -sf "$(pwd)/.pryrc" "$HOME/.pryrc"
ln -sf "$(pwd)/.xrayconfig" "$HOME/.xrayconfig"
ln -sf "$(pwd)/chruby/share/chruby" "$HOME/.local/share/chruby"
